import turtle as t

# "python" 출력 거북이
t_python = t.Turtle()
t_python.ht()

# 전구 켜기
def bulb_on() :
        t.shape('turtle')
        t.ht()
        t.pensize(3)
        t.speed(500)
        t.penup()
        t.setposition(-300,-150)
        t.pendown()
        t.begin_fill()
        t.fillcolor('yellow')
        t.setheading(180)
        t.lt(45)
        for cnt in range(4) :
                t.fd(20)
                t.lt(90)
                t.fd(20)
                t.rt(90)
        t.setheading(0)
        t.fd(100)
        t.lt(45)
        for cnt in range(4) :
                t.fd(20)
                t.lt(90)
                t.fd(20)
                t.rt(90)
        t.setheading(90)
        t.fd(50)
        t.setheading(225)
        for cnt in range(7) :
                t.fd(10)
                t.rt(90)
                t.fd(10)
                t.lt(90)
        t.setheading(270)
        t.fd(50)
        t.penup()
        t.fd(20)
        t.setheading(0)
        t.fd(50)
        t.pendown()
        t.circle(80)
        t.end_fill()
        t.bgcolor('white')
        # "python" 문자 넣기
        t_python.penup()
        t_python.setposition(0,20)
        t_python.pendown()
        t_python.pensize(5)
        t_python.pencolor('green')
        t_python.write("Python",False,"center",("",150))

# 전구 끄기
def bulb_off() :
        t.shape('turtle')
        t.ht()
        t.pensize(3)
        t.speed(500)
        t.penup()
        t.setposition(-300,-150)
        t.pendown()
        t.begin_fill()
        t.fillcolor('#4B4B4B')
        t.setheading(180)
        t.lt(45)
        for cnt in range(4) :
                t.fd(20)
                t.lt(90)
                t.fd(20)
                t.rt(90)
        t.setheading(0)
        t.fd(100)
        t.lt(45)
        for cnt in range(4) :
                t.fd(20)
                t.lt(90)
                t.fd(20)
                t.rt(90)
        t.setheading(90)
        t.fd(50)
        t.setheading(225)
        for cnt in range(7) :
                t.fd(10)
                t.rt(90)
                t.fd(10)
                t.lt(90)
        t.setheading(270)
        t.fd(50)
        t.penup()
        t.fd(20)
        t.setheading(0)
        t.fd(50)
        t.pendown()
        t.circle(80)
        t.end_fill()
        t.bgcolor('black')
        # "python" 지우기
        t_python.clear()

# 초기화면
t.shape('turtle')
t.ht()
t.pensize(3)
t.speed(0)
t.penup()
t.setposition(-300,-150)
t.pendown()
t.begin_fill()
t.fillcolor('#4B4B4B')
t.setheading(180)
t.lt(45)
for cnt in range(4) :
        t.fd(20)
        t.lt(90)
        t.fd(20)
        t.rt(90)
t.setheading(0)
t.fd(100)
t.lt(45)
for cnt in range(4) :
        t.fd(20)
        t.lt(90)
        t.fd(20)
        t.rt(90)
t.setheading(90)
t.fd(50)
t.setheading(225)
for cnt in range(7) :
        t.fd(10)
        t.rt(90)
        t.fd(10)
        t.lt(90)
t.setheading(270)
t.fd(50)
t.penup()
t.fd(20)
t.setheading(0)
t.fd(50)
t.pendown()
t.circle(80)
t.end_fill()
t.bgcolor('black')

# 스위치 모양
t_switch = t.Turtle()
t_switch.ht()
t_switch.speed(0)
t_switch.pensize(2)
t_switch.pencolor('red')

# 직사각형
t_switch.penup()
t_switch.setposition(300,-300)
t_switch.pendown()
t_switch.fd(50)
t_switch.lt(90)
t_switch.fd(100)
t_switch.lt(90)
t_switch.fd(50)
t_switch.lt(90)
t_switch.fd(100)
t_switch.bk(50)
t_switch.lt(90)
t_switch.fd(50)
t_switch.bk(25)
t_switch.lt(90)

# ↑ 모양
t_switch.penup()
t_switch.fd(10)
t_switch.pendown()
t_switch.fd(30)
t_switch.setheading(225)
t_switch.fd(10)
t_switch.bk(10)
t_switch.setheading(315)
t_switch.fd(10)
t_switch.bk(10)
t_switch.setheading(270)
t_switch.fd(30)
t_switch.setheading(0)
t_switch.write('on')
t_switch.setheading(270)

# ↓ 모양
t_switch.penup()
t_switch.fd(20)
t_switch.pendown()
t_switch.fd(10)
t_switch.setheading(0)
t_switch.write('off')
t_switch.setheading(270)
t_switch.fd(20)
t_switch.setheading(45)
t_switch.fd(10)
t_switch.bk(10)
t_switch.setheading(135)
t_switch.fd(10)
t_switch.bk(10)

# 키보드 입력
t.onkeypress(bulb_on, 'Up')
t.onkeypress(bulb_off, 'Down')
t.listen()
